---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: bom-components
  namespace: flux-system
spec:
  include:
    - repository:
        name: cluster-autoscaler
      toPath: components/required/cluster-autoscaler